// <auto-generated />
using System;
using DurableStack.Telemetry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DurableStack.Telemetry.Migrations.Telemetry
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260526155501_AddTelemetryRollupsAndWatermarks")]
    partial class AddTelemetryRollupsAndWatermarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("integer");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantPublicId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantPublicId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantPublicId", "ReceivedAtUtc");

                    b.ToTable("telemetry_batches", (string)null);
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryBucketRollup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketSize")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeartbeatCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunFailed")
                        .HasColumnType("integer");

                    b.Property<int>("RunRetried")
                        .HasColumnType("integer");

                    b.Property<int>("RunStarted")
                        .HasColumnType("integer");

                    b.Property<int>("RunSucceeded")
                        .HasColumnType("integer");

                    b.Property<string>("TenantPublicId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("BucketSize", "BucketStartUtc");

                    b.HasIndex("TenantPublicId", "BucketSize", "BucketStartUtc")
                        .IsUnique();

                    b.ToTable("telemetry_bucket_rollups", (string)null);
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Attempt")
                        .HasColumnType("integer");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("HeartbeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("JobName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("RunId");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.HasIndex("OccurredAtUtc", "BatchId");

                    b.HasIndex("WorkerName", "OccurredAtUtc");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryFailureGroupRollup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketSize")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantPublicId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("BucketSize", "BucketStartUtc");

                    b.HasIndex("TenantPublicId", "BucketSize", "BucketStartUtc", "JobName", "ErrorType", "ErrorMessage")
                        .IsUnique();

                    b.ToTable("telemetry_failure_group_rollups", (string)null);
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryRollupWatermark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketSize")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("LastRolledUpBucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantPublicId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantPublicId", "BucketSize")
                        .IsUnique();

                    b.ToTable("telemetry_rollup_watermarks", (string)null);
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryEvent", b =>
                {
                    b.HasOne("DurableStack.Telemetry.Entities.TelemetryBatch", "Batch")
                        .WithMany("Events")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("DurableStack.Telemetry.Entities.TelemetryBatch", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
